added some extra flags to makefile test rule

diff --git a/cpp/cpp_07/ex00/Makefile b/cpp/cpp_07/ex00/Makefile
--- a/cpp/cpp_07/ex00/Makefile
+++ b/cpp/cpp_07/ex00/Makefile
@@ -13,46 +13,48 @@ FILES=main
 OBJS=$(addprefix $(OBJ_DIR), $(addsuffix .o, $(FILES)))
 SRC=$(addprefix $(SRC_DIR), $(addsuffix .cpp, $(FILES)))
 
-TEST_FILES=test_main test_whatever
+TEST_FILES=test_whatever
 TEST=$(addprefix $(TEST_DIR), $(addsuffix .cpp, $(TEST_FILES)))
-TEST_EXEC=./test_$(NAME)
+TEST_EXEC=./tests/tester_$(NAME)
 
 VALID=\033[0;32m
 
 all: $(NAME)
 
 $(NAME): $(OBJS)
-	@$(CPP) $(FLAGS) $(INCLUDES) -o $@ $^
-	@echo "$(VALID)exec compiled as: $(NAME)"
+	$(CPP) $(FLAGS) $(INCLUDES) -o $@ $^
+	echo "$(VALID)✔ exec compiled as: $(NAME)"
 
 $(OBJ_DIR)%.o: $(SRC_DIR)%.cpp
-	@mkdir -p $(OBJ_DIR)
-	@$(CPP) $(FLAGS) $(INCLUDES) -c $< -o $@
-	@echo "$(VALID)objs compiled"
+	mkdir -p $(OBJ_DIR)
+	$(CPP) $(FLAGS) $(INCLUDES) -c $< -o $@
+	echo "objs compiled"
 
 doc:
-	@doxygen Doxyfile
-	@echo "$(VALID)doc generated"
+	doxygen Doxyfile
+	echo "$(VALID)doc generated"
 
 test: $(TEST)
-	@$(CPP) $(FLAGS) $(INCLUDES) $(TEST) -o $(TEST_EXEC)
-	@$(TEST_EXEC) || (echo "$(RED)Tests failed!$(RESET)" && exit 0)
+	$(CPP) $(FLAGS) $(INCLUDES) $(TEST) -o $(TEST_EXEC)
+	$(TEST_EXEC) -s || (echo "$(RED)Tests failed!$(RESET)" && exit 0)
 
 debug:
-	@gdb $(NAME)
+	gdb -tui $(NAME)
 
 clean:
-	@rm -rf $(OBJ_DIR)
-	@echo "objs cleaned"
+	rm -rf $(OBJ_DIR)
+	echo "objs cleaned"
 
 fclean: clean
-	@rm -rf $(DOC_DIR)
-	@echo "doc cleaned"
-	@rm -f $(TEST_EXEC)
-	@echo "test cleaned"
-	@rm -f $(NAME)
-	@echo "exec cleaned"
+	rm -rf $(DOC_DIR)
+	echo "doc cleaned"
+	rm -f $(TEST_EXEC)
+	echo "test cleaned"
+	rm -f $(NAME)
+	echo "exec cleaned"
 
 re: fclean all
 
 .PHONY: all doc test debug clean fclean re
+.SILENT:
+.DELETE_ON_ERROR:
